### ISSUE TITLE
v49 crash (A3wasteland)

### ISSUE THREAD

**Issue by Jermin** [Torndeco/extDB2#38] opened 2015-04-09 14:27 UTC
I've pulled the latest commits of the extDB2_beta branch of A3wasteland and updated extDB2 to v49. 

After starting the server, I found below errors in the rptlog:

```
 22:04:07 Error in expression <ult = call compile _queryResult;
 
 
 if ((_queryResult select 0) isEqualTo 0) exit>
 22:04:07   Error position: <_queryResult select 0) isEqualTo 0) exit>
 22:04:07   Error Undefined variable in expression: _queryresult
 22:04:07 File mpmissions\__cur_mp.Altis\persistence\server\setup\extDB\async_database.sqf, line 63
 22:04:07 Error in expression <

 _objects pushBack _objData;
 } forEach _result;

 _objects
 >
 22:04:07   Error position: <_result;

 _objects
 >
 22:04:07   Error Undefined variable in expression: _result
 22:04:07 File mpmissions\__cur_mp.Altis\persistence\server\world\extDB\getObjects.sqf, line 59
```
After the server has run for about 30 minutes, the extDB crashed, which caused the server to crash. The extDB log showed:

```
extDB2: Version: 49
extDB2: Linux Version
Message: Donated to extDB2 Develeopment ?
Message: All development for extDB2 is done on a Linux Dedicated Server
Message: Donate Link https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=2SUEFTGABTAM2
Message: Leave a message if there is a feature you would like to see added.
Message: Thanks for all the people that have donated.
Message: Torndeco: 20/02/15


extDB2: Found extdb-conf.ini
extDB2: Detected 8 Cores, Setting up 6 Worker Threads


[22:04:05 +08:00] [Thread 2431664196] extDB2: Database Type: MySQL
[22:04:05 +08:00] [Thread 2431664196] extDB2: Database Session Pool Started
[22:04:05 +08:00] [Thread 2431664196] extDB2: SQL_CUSTOM: Loading Template Filename: /home/server/arma3/a3_server0/@extDB2/extDB/sql_custom/a3wasteland.ini
[22:04:05 +08:00] [Thread 2431664196] extDB2: LOCK START
[22:04:05 +08:00] [Thread 2431664196] extDB2: LOCK STOP
[22:04:05 +08:00] [Thread 2431664196] 
[22:04:06 +08:00] [Thread 2431664196] extDB2: LOCK START
[22:04:06 +08:00] [Thread 2431664196] extDB2: LOCK STOP
[22:04:06 +08:00] [Thread 2431664196] 
[22:04:06 +08:00] [Thread 2431664196] extDB2: LOCK START
[22:04:06 +08:00] [Thread 2431664196] extDB2: LOCK STOP
[22:04:06 +08:00] [Thread 2431664196] 
[22:04:07 +08:00] [Thread 2431664196] extDB2: LOCK START
[22:04:07 +08:00] [Thread 2431664196] extDB2: LOCK STOP
[22:04:07 +08:00] [Thread 2431664196] 
[22:04:07 +08:00] [Thread 2431664196] extDB2: LOCK START
[22:04:07 +08:00] [Thread 2431664196] extDB2: LOCK STOP
[22:04:07 +08:00] [Thread 2431664196] 
[22:04:07 +08:00] [Thread 2431664196] extDB2: LOCK START
[22:04:07 +08:00] [Thread 2431664196] extDB2: LOCK STOP
[22:04:07 +08:00] [Thread 2431664196] 
[22:04:07 +08:00] [Thread 2431664196] extDB2: LOCK START
[22:04:07 +08:00] [Thread 2431664196] extDB2: LOCK STOP
[22:04:07 +08:00] [Thread 2431664196] 
[22:04:07 +08:00] [Thread 2431664196] extDB2: LOCK START
[22:04:07 +08:00] [Thread 2431664196] extDB2: LOCK STOP
[22:04:07 +08:00] [Thread 2431664196] 
[22:05:03 +08:00] [Thread 2431664196] extDB2: LOCK START
[22:05:03 +08:00] [Thread 2431664196] extDB2: LOCK STOP
[22:05:03 +08:00] [Thread 2431664196] 
[22:05:11 +08:00] [Thread 2431664196] extDB2: LOCK START
[22:05:11 +08:00] [Thread 2431664196] extDB2: LOCK STOP
[22:05:11 +08:00] [Thread 2431664196] 
[22:05:11 +08:00] [Thread 2431664196] extDB2: LOCK START
[22:05:11 +08:00] [Thread 2431664196] extDB2: LOCK STOP
[22:05:11 +08:00] [Thread 2431664196] 
[22:05:11 +08:00] [Thread 2431664196] extDB2: LOCK START
[22:05:11 +08:00] [Thread 2431664196] extDB2: LOCK STOP
[22:05:11 +08:00] [Thread 2431664196] 
[22:05:14 +08:00] [Thread 2431664196] extDB2: LOCK START
[22:05:14 +08:00] [Thread 2431664196] extDB2: LOCK STOP
[22:05:14 +08:00] [Thread 2431664196] 
[22:05:18 +08:00] [Thread 2431664196] extDB2: LOCK START
[22:05:18 +08:00] [Thread 2431664196] extDB2: LOCK STOP
[22:05:18 +08:00] [Thread 2431664196] 
[22:05:18 +08:00] [Thread 2431664196] extDB2: LOCK START
[22:05:18 +08:00] [Thread 2431664196] extDB2: LOCK STOP
[22:05:18 +08:00] [Thread 2431664196] 
[22:05:18 +08:00] [Thread 2431664196] extDB2: LOCK START
[22:05:18 +08:00] [Thread 2431664196] extDB2: LOCK STOP
[22:05:18 +08:00] [Thread 2431664196] 
[22:05:24 +08:00] [Thread 2431664196] extDB2: LOCK START
[22:05:24 +08:00] [Thread 2431664196] extDB2: LOCK STOP
[22:05:24 +08:00] [Thread 2431664196] 
[22:05:39 +08:00] [Thread 2431664196] extDB2: LOCK START
[22:05:39 +08:00] [Thread 2431664196] extDB2: LOCK STOP
[22:05:39 +08:00] [Thread 2431664196] 
[22:05:39 +08:00] [Thread 2431664196] extDB2: LOCK START
[22:05:39 +08:00] [Thread 2431664196] extDB2: LOCK STOP
[22:05:39 +08:00] [Thread 2431664196] 
[22:05:39 +08:00] [Thread 2431664196] extDB2: LOCK START
[22:05:39 +08:00] [Thread 2431664196] extDB2: LOCK STOP
[22:05:39 +08:00] [Thread 2431664196] 
[22:05:49 +08:00] [Thread 2431664196] extDB2: LOCK START
[22:05:49 +08:00] [Thread 2431664196] extDB2: LOCK STOP
[22:05:49 +08:00] [Thread 2431664196] 
[22:05:56 +08:00] [Thread 2431664196] extDB2: LOCK START
[22:05:56 +08:00] [Thread 2431664196] extDB
```

**Comment by Torndeco** [comment] 2015-04-09 18:35
Full RPT Log
Nothing there highlights extDB crashed the server, just i left debug code infor timing mutex locks

**Comment by Jermin** [comment] 2015-04-10 01:17
Here it is: https://drive.google.com/file/d/0B45RfM_I1koTMWJ5d0hNSlRKWGM/view?usp=sharing

**Comment by Jermin** [comment] 2015-04-10 01:17
Here it is: https://drive.google.com/file/d/0B45RfM_I1koTMWJ5d0hNSlRKWGM/view?usp=sharing

**Comment by Torndeco** [comment] 2015-04-10 01:27
Nothing in that log file mentions any crash at all.
More than likely your crash is a bug in armaserver, since you encountered after recent patch.

extDB2 on linux still has debugging info in it.
So you can always run armaserver in gdb + do a backtrace when/if server crashes.
That way you can find out what is causing the crash, if its armaserver or an extension.

Very little has changed in extDB2, so i highly doubt extension is crashing.

Also pastebin its alot easier to read thanks

**Comment by Jermin** [comment] 2015-04-10 14:01
But uniforms, vests and objects are not saved. And there are errors in \persistence\server\setup\extDB\async_database.sqf and persistence\server\world\extDB\getObjects.sqf.

**Comment by Torndeco** [comment] 2015-04-10 14:32
Those problems are for A3Wasteland Github for extDB2
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/tree/extDB2_beta
There are other people that have it running etc fine

This repo is for the extension itself, not for issues with another mission SQF Code etc...

---------

Anyway closing issue
Until you get a log or gdb traceback of a crash caused by extDB2.

**Closed by Torndeco** 2015-04-10 14:32 UTC
