### ISSUE TITLE
Server crash with RCON

### ISSUE THREAD

**Issue by xunclex** [Torndeco/extDB2#63] opened 2015-05-29 06:43 UTC
On server restart, if players joined to server before "mission reading complete" (-autoInit),  process just crash.

This began after we started using rcon protocol. If i set sleep 5 before rcon ADD_PROTOCOL call, server loading fine, but sometimes crash anyway.

May be i need add sleep between all calls? Or the order of calls are wrong? (add database -> SQL_CUSTOM_V2 -> LOG -> MISC -> RCON -> lock)

p.s.: sorry for my english

**Comment by xunclex** [comment] 2015-05-29 07:31
my fix is "sleep 40" before all extdb calls in life_server/init.sqf

10:12:47 Roles assigned.
10:12:47 Reading mission ...
10:13:18 Mission read.
10:13:19 Game started.

10:14:00 "extDB2: Version: 59"
10:14:00 "extDB2: RCON is enabled"
10:14:00 "extDB2: SPY_LOG is successfully added"
10:14:00 "extDB2: MISC is enabled"
10:14:00 "extDB2: Connected to Database"

**Comment by Torndeco** [comment] 2015-05-29 08:02
I need to see debug extdb2 logs from a server crash.

**Comment by xunclex** [comment] 2015-05-29 08:13
http://pastebin.com/sX9ytVpG

**Comment by Torndeco** [comment] 2015-05-29 08:24
RPT as well from a crash thanks

**Comment by xunclex** [comment] 2015-05-29 08:35
http://pastebin.com/70YvGB85

**Comment by Torndeco** [comment] 2015-05-29 12:55
You using playerkicking or whitelisting ?

**Comment by xunclex** [comment] 2015-05-29 13:03
only bans with rcon "addban" in spyglass checks.

**Comment by Torndeco** [comment] 2015-05-29 13:07
I will add some extra debug output for rcon in the next release.
But i am unable to reproduce the crash or see any issue in the code atm.

Also in future please send logs from the same crash instance.

**Comment by Torndeco** [comment] 2015-05-31 16:35
Closing until someone can reproduce this etc...

**Comment by xunclex** [comment] 2015-05-31 21:37
for reproduce you need connect to server at setup step.

http://i.imgur.com/YKMEz78.jpg

so, when mission reading completed we have two connects at the same time: player connect & rcon admin connect. 

http://i.imgur.com/ALJXmjh.jpg

if make sleep before rcon add, and let all players connect to server - no crash at all

server starting with -autoInit option
i can record video for HOWTO reproduce this error.

**Comment by Torndeco** [comment] 2015-05-31 22:27
Found the issue, stupid mistake
Highly recommend you disable RCON till i get a new release out tomorrow
Its not thread safe atm

**Comment by chris579** [comment] 2015-05-31 22:30
Could reproduce this aswell but without -autoInit it is working fine.

**Comment by Torndeco** [comment] 2015-06-02 03:38
Should be working fine now with v61
No Linux builds atm will be in next day or 2

**Comment by xunclex** [comment] 2015-06-02 12:18
Thanks a lot! Our anti-cheat system and some rules (new life zone, etc) depend from rcon, so now all works fine.

P.S.
We had nice online (130 players) before summer vacation and always use last release of extdb. If u need some tests - at your service

**Comment by xunclex** [comment] 2015-06-02 17:19
I have bad news. 
Bug is not fixed, same crashes...

**Comment by Torndeco** [comment] 2015-06-02 17:56
I need logs RPT extdb debug logs and battleye logs

**Comment by Torndeco** [comment] 2015-06-02 17:57
Also logs from same crash not logs from different crashes

**Comment by xunclex** [comment] 2015-06-02 18:11
http://pastebin.com/EmPS83nt
http://pastebin.com/56AGFM0r

and BE

﻿20:21:22 : Rcon client logging in
﻿20:21:39 : RCon admin #0 (109.197.8.9:62281) logged in
﻿20:21:39 : RCon admin #1 (127.0.0.1:59814) logged in
﻿20:21:39 : RCon admin #2 (5.251.134.109:64329) logged in
﻿20:21:39 : RCon admin #3 (46.39.231.165:64001) logged in
﻿20:21:39 : Player #0 [AFF] Dyuk (176.194.248.41:2304) connected
﻿20:21:39 : Player #1 [St.Sergeant] Donbass (31.174.153.253:2304) connected
﻿20:21:39 : Player #2 Alexey (95.25.156.73:2304) connected
﻿20:21:39 : Player #3 [SDR] Dragonborn (85.115.248.233:20839) connected
﻿20:21:39 : Player #4 [AFF] VIKTOR (31.181.218.203:2304) connected
﻿20:21:52 : RCon admin #4 (127.0.0.1:59815) logged in
﻿20:21:52 : Lost Connection!
﻿20:21:52 : Closing socket & exiting!

**Comment by xunclex** [comment] 2015-06-02 18:21
But at development server, when i try reproduce error - everything fine. 
may be it happens, because we have few dart admins and BEC at local? and if all connecting at same time - boom!

**Comment by Torndeco** [comment] 2015-06-03 04:54
Send me a skype message Torndeco + i can send you a test build.
Believe i got last of the bugs sorted, just need someone that is able to reproduce to check it out.

Saves me having to program some test clients to reproduce the problem

**Comment by xunclex** [comment] 2015-06-03 09:13
Done (from skype x_uncle_x)

**Comment by chris579** [comment] 2015-06-03 18:59
Currently I have instant crashes upon server start when the first player connects. Having version 61 and extDB is not even creating logs. With RCON disabled it works fine

**Comment by Torndeco** [comment] 2015-06-04 13:29
Should be fixed now

**Closed by Torndeco** 2015-06-04 13:29 UTC
Labels: bug
